version: 2.0.{build}
build_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: CLlvxILVD81use5kelg4ltghYgDlGHWszffiwGwKc1fYSi3k9POLzwEpodroDjRf
  on:
    branch: master
    appveyor_repo_tag: true